const actionTypes = {
    FETCH_BOOKS_REQUEST: "FETCH_BOOKS_REQUEST",
    FETCH_BOOKS_SUCCESS: "FETCH_BOOKS_SUCCESS",
    FETCH_BOOKS_FAILURE: "FETCH_BOOKS_FAILURE",
    UPDATE_BOOKS_SUCCESS: "UPDATE_BOOKS_SUCCESS"
}

export default actionTypes;
