const actionTypes = {
    FETCH_BOOKS_REQUEST: "FETCH_BOOKS_REQUEST",
    FETCH_BOOKS_SUCCESS: "FETCH_BOOKS_SUCCESS",
    FETCH_BOOKS_FAILURE: "FETCH_BOOKS_FAILURE",
    ADD_BOOK_SUCCESS: "ADD_BOOK_SUCCESS",
    DELETE_BOOK_SUCCESS: "DELETE_BOOK_SUCCESS"
}

export default actionTypes;
